language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "python setup.py install"
  - "pip install -r test_requirements.txt"
  - "pip install flake8==2.1.0"
before_script:
  - "flake8 --ignore=E501 mapmyfitness"
# command to run tests
script:
    nosetests --with-coverage --cover-package mapmyfitness
after_script:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
